### ISSUE TITLE
Erro de conexão

### ISSUE THREAD

**Issue by luckasiqueira** [SirSavio/alura-downloader#13]
Opa o/

Estou tentando rodar o script para baixar alguns cursos, mas sempre dá erro de login.
Abaixo, editei a conta para simular o erro que acontece quando coloco os dados corretos.
Tenho certeza de que os dados estão corretos, mas mesmo assim não conecta.

Alguma ideia do que poderia ser?

![Captura de tela de 2023-09-09 22-28-46](https://github.com/SirSavio/alura-downloader/assets/66996105/62c28ab9-c5e0-4588-97b6-3f743b592285)

**Comment by akupac** [comment]
Estou com o mesmo erro, rodando no Ubuntu 22.04.

Que tipo de informação pode ajudar?

**Comment by mgnischor** [comment]
Creio que mudaram a forma de autenticação, não que seja um problema no código aqui...

https://imgur.com/a/3N5ordD

Testado no Thunder Client do Visual Studio Code

**Comment by ClaytonPaiva** [comment]
Há alguma forma de contornar isso?

**Comment by RenatoMartinsXrd** [comment]
Tem sim mudando essa linha aqui
` 'User-Agent': 'alura-mobi/android-79'`
`  'User-Agent': 'alura-mobi/android'`

**Comment by SirSavio** [comment]
Fechando a issue após o merge do PR do @RenatoMartinsXrd
