### ISSUE TITLE
Projeto Abandonado HELP

### ISSUE THREAD

**Issue by RenatoMartinsXrd** [SirSavio/alura-downloader#21]
Pessoal, não sei o que aconteceu, mas esse projeto foi abandonado, fiz um PR para ajustar alguns bugs e manter o funcionamento do script, porém até agora nenhuma resposta ou review, o PR é esse https://github.com/SirSavio/alura-downloader/pull/17

Eu fiz um fork no meu repositorio com as correções, confesso que não testei mais e não tenho certeza se ainda funciona, na época depois das correções funcionou tudo normalmente, minha intenção era apenas contribuir por aqui mesmo e não fazer um fork com interesse em meu auto-promover, mas deixo aqui meu fork para caso alguém precise usar!
https://github.com/RenatoMartinsXrd/alura-downloader

**Comment by SirSavio** [comment]
Boa tarde! Aprovei o seu merge, estive bastante ocupado por esses últimos meses, irei dar uma atualizada no projeto para voltar a funcionar essa final de semana!
