### ISSUE TITLE
Get_course() não retornando informações do curso

### ISSUE THREAD

**Issue by buck999** [SirSavio/alura-downloader#6]
Olá, ao executar o script, o get_course() na linha 130 não consegue pegar as informações do curso. Tentei fazer o que falaram e dar play em algum video do curso antes, mas sem sucesso. O status do retorno do get_course() é um 403 forbidden. Alguma ideia do que seja?

**Comment by i4m-bruno** [comment]
403 significa não autorizado! acho que mudaram o user-agent. tem que interceptar a rede do smartphone e ver qual user-agent o aplicativo está enviando. feito isso só atualizar no código no método get_course()

**Comment by angeloevangelista** [comment]
> 403 significa não autorizado! acho que mudaram o user-agent. tem que interceptar a rede do smartphone e ver qual user-agent o aplicativo está enviando. feito isso só atualizar no código no método get_course()

Abri uma PR. Um dos problemas era esse mesmo. Foi adicionado um _-79_ no final, pelo que lembro. O outro eram os cookies que era retornados

**Comment by SirSavio** [comment]
Aprovado o PR do @angeloevangelista com as correções!
