### ISSUE TITLE
Não está funcionando mais!

### ISSUE THREAD

**Issue by julianoaj** [SirSavio/alura-downloader#8]
Olá, o script não está funcionando mais!

Acredito que seja algum problema na API, porem não tenho conhecimento o suficiente para concertar. :(

URL que estou usando: https://cursos.alura.com.br/course/vue3-comecando-framework/

Erro que me está sendo retornado:
[INFO] ID COURSE: undefined | SLUG: UNDEFINED | NAME: UNDEFINED | COURSE TIME: undefined

(node:14088) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at main (C:\Users\Alison Juliano\Documents\Scripts\alura-downloader\index.js:48:31)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14088) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1) 
(node:14088) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by i4m-bruno** [comment]
dei um console.log no res.body e vi que tão metendo um 403 (não autorizado). Acredito que atualizaram o user-agent

**Comment by passosedu** [comment]
Testei hoje. Não tá funcionando mesmo @SirSavio 
Contamos com vc para atualizar e nos salvar. Abraços e muito obrigado pelo seu trabalho.

**Comment by angeloevangelista** [comment]
Eu consegui arrumar aqui de uma forma toda zoada porque precisava baixar um curso e meu acesso encerra amanhã kkkkk (tenso) 

Amanhã eu corrijo do jeito certo e abro uma PR

**Comment by SirSavio** [comment]
Aprovei o PR do @angeloevangelista, valeu pelo tempo! A Alura vira e mexe muda a forma como valida as coisas e acaba quebrando. Vou dar como finalizado esse issue,
